if: branch = travis_test

dist: xenial
git:
  depth: false
language: go
go:
- 1.11.x
services:
- docker
env:
  global:
  - GO111MODULE=on
before_install:
- echo -e "machine github.com\n  login $CI_USER_TOKEN" > ~/.netrc
- nvm install 12
#- travis_retry yarn --cwd ui/v2.5 install --frozen-lockfile
#- make generate
#- CI=false yarn --cwd ui/v2.5 build-ci
#- go get -v github.com/mgechev/revive
script:
# left lint off to avoid getting extra dependency
#- make lint
#- make fmt-check vet it
after_success:
#- docker pull stashapp/compiler:develop
#- sh ./scripts/cross-compile.sh
before_deploy:
# push the latest tag when on the develop branch
- export RELEASE_DATE=$(date +'%Y-%m-%d %H:%M:%S %Z')
- export STASH_VERSION=v999
# set TRAVIS_TAG explcitly to the version so that it doesn't pick up latest_develop
- if [ "$TRAVIS_BRANCH" = "master"]; then export TRAVIS_TAG=${STASH_VERSION}; fi
deploy:
  # latest develop release
  - provider: releases
    api_key:
      secure: wknN18XuRTsTw9/W6cYqOcCrjCI5fRt+iIeteP9mq73m9e9sE7ZqsX0FhQUuGGyTGB0tR7mLBVA/QGFJIBNbxAEQ40elU/vPjgY+pkbOtoHQyedgevMZAvNXnWywpxTCCxlpZdM+YUwAV3loBFaqPQ8dVsE4ijb9tigEWcZnoXcx4rasKRPN3ERk0YZvCnbmLU5aTOOMfHbyLySKBCsjgGT/4qoGJncI7Di2Mf+bcFd23S2EQ8dWoqmgDH4DRWQKkX5CRdnMcmqCJo1MC4dE6mt4dLxU9mne56yieOJUZ2DHvYnOJmCZxn0c4k60vXQ8SskCc7Hs/WlqP2L3qFHRFuraf/qpT+Wle9LLjaDzSRyimTnEY7JmqndyqVzmvMVaM/SWF9R4zXcRqDyh6PPNadQ4J4EZ2agEvB4Rth9P4z6aC7JnYQW3hSPUCos1YMwVQ58EL8zrnT5nQVMyZb0BjsUIwK45E++HK1g4Uk6kqwnpei0JkzUGsvIvoocClg463UYECG85//iAiitCv0pqR6JIRdGogNdPeFMv41Mk4w3QbFX3/LWjAIreSevF/J91zxQpjLrM+iPOlFSgrP0B9NUwD/ykYJOpIxPh1iAV/7bazFSZLDU/gtxm2Iobk5fDBJIwyZHjrDHFolZmzHutnnW857Hs8RHqCIkJuwl04HU=
    file:
    - README.md
    skip_cleanup: true
    overwrite: true
    name: "${STASH_VERSION}: Latest development build"
    body: "${RELEASE_DATE}: This is always the latest committed version on the develop branch. Use as your own risk!"
    prerelease: true
    on:
      repo: WithoutPants/stash
      branch: travis_test
