# leave empty for all addresses on localhost
host: ""
# port for local server
port: 9998
# stash server
server_url: http://192.168.1.66:9999
# path to ffmpeg on local machine
ffmpeg_path: D:\dev\stash_data\sfw\ffmpeg.exe
ffprobe_path: D:\dev\stash_data\sfw\ffprobe.exe

# logs to stdout by default. Uncomment to log to file instead.
# log_file: log.txt

# uncomment for debug level logging
# log_debug: true