name: Build

on:
  push:
    branches: [ develop, master, action-test ]
  pull_request:
    branches: [ develop ]
  release:
    types: [ published ]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2

    - name: Checkout
      run: git fetch --prune --unshallow --tags

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.13

    - name: Set up Node
      uses: actions/setup-node@v2
      with:
        node-version: '12'
    
    - name: Cache node modules
      uses: actions/cache@v2
      env:
        cache-name: cache-node_modules
      with:
        path: ui/v2.5/node_modules
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('ui/v2.5/yarn.lock') }}

    - name: Pre-install
      run: make pre-ui

    - name: Generate
      run: make generate
    
    - name: Build UI
      run: make ui-only